n_jobs: 4
num_workers: 4


videoclip:
  use: True
  T: 8  # Number of consecutive frames for forward-prop.

  overlap: 8
  root: C:/Users/ioankont/PycharmProjects/SalViT360-main (1)/SalViT360-main


w: 1920 
h: 960

path_gts: "D:\Program Files\IoanProjects\Vrdata3\fixation"
path_gtf: "D:\Program Files\IoanProjects\Vrdata3\fixation"
name: "VREyeTracking"

