Config: 'TSalV360'

wandb:
    project: "TSalV360"
    name: ""

phase:
    name: 'train'  # train, test
paths:
    path_to_text_saliency_maps: "/m2/ioankont/test/text_saliency_maps"
    path_to_erp_frames: "/m2/ioankont/test/data"
    save_model_folder: "model"
network:
    backbone: CLIP

    VSTCA:
        depth: 1
        num_heads: 8
        mlp_dim: 4
        ff_dropout: 0.0
        attn_dropout: 0.4
        multihead: True
        new_posemb: True

    decoder:
        mode: tangent  # erp | hybrid | tangent
        norm_layer: layernorm  # layernorm | none
train:

    batch_size: 8
    clip_size: 8 #prediction per 8 erp frames (clip size)
    use_data_augmentation: True

    epochs: 4

    optim_algorithm: AdamW

    dataset_folds_file: "dataset/kfold_splits.json"
    optim:
        AdamW:
            lr: 0.00001
            betas: [ 0.9, 0.999 ]
            weight_decay: 0.01
    criterion:
        weights:
            kl: 1.0
            cc: 0.05
            #nss: 0.05  # weight of SMSE as well

tangent_images:
    fov: 80
    nrows: 4
    npatches: 18
    patch_size:
        e2p: [224, 224]
